
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prices
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Local development uses 'db' host, production will use claw.cloud URL
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:password@db:5432/prices}
      - API_URL=https://sfl.world/api/v1/prices

volumes:
  pgdata:
